spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/sennofit_insole_app

grpc:
  port: 50512
  enabled: true

cos:
  folder:
    report: test/report
  bucketName: sennofit-test-1255704943
  endpoint: https://sennofit-test-1255704943.cos.ap-shanghai.myqcloud.com