spring:
  data:
    mongodb:
      uri: mongodb://yan:yan@10.0.4.21:27017/sennofit_insole_app
  redis:
    host: 172.81.230.245
    port: 6379
    password: Sennotech2015
    database: 10
cos:
  folder:
    report: test/report
  bucketName: sennofit-test-1255704943
  endpoint: https://sennofit-test-1255704943.cos.ap-shanghai.myqcloud.com

senno:
  algo:
    root: http://office10.sennoapi.com/posture/v2.0
  directory:
    temp: /app/tmp
  notification:
    posture: https://dev.fit.sennoapi.com/ws/reports/notification/posture
    video: https://dev.fit.sennoapi.com/ws/reports/notification/video